/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloConnection.ConexaoBD;
import modeloDao.DaoCampoQuadra;
import modeloBens.BeansCampoQuadra;
import modeloBens.ModeloTabela;



/**
 *
 * @author F-BRAGA
 */
public class TelaCadCampo extends javax.swing.JFrame {
    BeansCampoQuadra mod = new BeansCampoQuadra();
    DaoCampoQuadra control = new DaoCampoQuadra();
    ConexaoBD conex = new ConexaoBD();
    int flag = 0;
    

    /**
     * Creates new form TelaCadCampo
     */
    public TelaCadCampo() {
        initComponents();
        preencherTabela("SELECT * FROM localjogo ORDER BY nome");//classificar tabela por nome
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLocaisJogos = new javax.swing.JTable();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonpesquisar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTCOD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel2.setText("Nome");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 30, 60, 20);

        jLabel3.setText("Categoria");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1196, 13, 47, 14);

        jTextFieldNome.setEnabled(false);
        jPanel1.add(jTextFieldNome);
        jTextFieldNome.setBounds(30, 50, 352, 30);

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Society", "Campo", "Futsal" }));
        jComboBoxCategoria.setEnabled(false);
        jComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxCategoria);
        jComboBoxCategoria.setBounds(420, 50, 160, 30);

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNovo);
        jButtonNovo.setBounds(20, 430, 59, 23);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalvar);
        jButtonSalvar.setBounds(100, 430, 65, 23);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar);
        jButtonCancelar.setBounds(190, 430, 90, 23);

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExcluir);
        jButtonExcluir.setBounds(410, 430, 65, 23);

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditar);
        jButtonEditar.setBounds(300, 430, 74, 23);

        jTableLocaisJogos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableLocaisJogos.setEnabled(false);
        jTableLocaisJogos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLocaisJogosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLocaisJogos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 140, 700, 280);
        jPanel1.add(jTextFieldPesquisa);
        jTextFieldPesquisa.setBounds(30, 100, 360, 30);

        jButtonpesquisar.setText("pesquisar");
        jButtonpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonpesquisar);
        jButtonpesquisar.setBounds(420, 100, 130, 30);

        jLabel4.setText("ID");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 10, 30, 14);

        jTCOD.setEnabled(false);
        jPanel1.add(jTCOD);
        jTCOD.setBounds(70, 10, 130, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Cadastro de Locais de Jogos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel1)
                .addContainerGap(232, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(741, 568));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoriaActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if(jTextFieldNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o NOME para continuar");
            jTextFieldNome.requestFocus();
        }else
        if(flag==1){
        mod.setNome(jTextFieldNome.getText());  
        control.Salvar(mod);
        jTextFieldNome.setText("");
        jTextFieldNome.setEnabled(false);
        jComboBoxCategoria.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
      preencherTabela("SELECT * FROM localjogo ORDER BY nome");    
        }else{
        mod.setCodigo((Integer.parseInt(jTCOD.getText())));
        mod.setNome(jTextFieldNome.getText());
        control.Editar(mod);
        jTCOD.setText(null);
        jTextFieldNome.setText(null);        
        jTextFieldNome.setEnabled(false);
        jComboBoxCategoria.setEnabled(false);//verificar a categoria depois
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonCancelar.setEnabled(false);
        preencherTabela("SELECT * FROM localjogo ORDER BY nome");
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        jTextFieldNome.setEnabled(true);
        jComboBoxCategoria.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jTCOD.setText("");
        jTextFieldNome.setText("");
        jTextFieldPesquisa.setText("");
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jTextFieldPesquisa.setEnabled(false);
        jButtonpesquisar.setEnabled(false); 
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpesquisarActionPerformed
        mod.setPesquisa(jTextFieldPesquisa.getText());
        BeansCampoQuadra model = control.buscaCampoQuadra(mod);
        jTextFieldNome.setText(model.getNome());
        jTCOD.setText(String.valueOf(model.getCodigo()));
        preencherTabela("SELECT * FROM localjogo WHERE nome LIKE '%"+mod.getPesquisa()+"%'");

    }//GEN-LAST:event_jButtonpesquisarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldNome.setEnabled(!true);
        jComboBoxCategoria.setEnabled(!true);
        jButtonSalvar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jTextFieldPesquisa.setEnabled(true);
        jButtonpesquisar.setEnabled(true);
        jTCOD.setText("");
        jTextFieldNome.setText(""); 
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 2;
        jTextFieldNome.setEnabled(true);
        jComboBoxCategoria.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);  
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        if(resposta == JOptionPane.YES_OPTION){
            mod.setCodigo(Integer.parseInt(jTCOD.getText()));
            control.Excluir(mod);
        jTCOD.setText(null);
        jTextFieldNome.setText(null);        
        jTextFieldNome.setEnabled(false);
        jComboBoxCategoria.setEnabled(false);//verificar a categoria depois
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonCancelar.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        preencherTabela("SELECT * FROM localjogo ORDER BY nome");
        }
        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableLocaisJogosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLocaisJogosMouseClicked
       String campo =""+jTableLocaisJogos.getValueAt(jTableLocaisJogos.getSelectedRow(), 1);
       conex.conexao();
       conex.executaSql("SELECT * FROM localjogo WHERE nome='"+campo+"'");
        try {
            conex.rs.first();
            jTCOD.setText(String.valueOf(conex.rs.getInt("codigo")));
            jTextFieldNome.setText(conex.rs.getString("nome"));
            JOptionPane.showMessageDialog(null, "Erro ao dados");
            ConexaoBD conexPesquisa = new ConexaoBD();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados"+ex);
        }
       conex.desconectar();
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);       
       
    }//GEN-LAST:event_jTableLocaisJogosMouseClicked
    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"codigo", "nome"};
        conex.conexao();
        conex.executaSql(Sql);
        try{
            conex.rs.first();
            do{
                dados.add(new Object[]{conex.rs.getInt("codigo"), conex.rs.getString("nome")});
            }while(conex.rs.next());
        
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Insira um local cadastrado!");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableLocaisJogos.setModel(modelo);
        jTableLocaisJogos.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableLocaisJogos.getColumnModel().getColumn(0).setResizable(false);
        jTableLocaisJogos.getColumnModel().getColumn(1).setPreferredWidth(501);
        jTableLocaisJogos.getColumnModel().getColumn(1).setResizable(false);
        jTableLocaisJogos.getTableHeader().setReorderingAllowed(false);
        jTableLocaisJogos.setAutoResizeMode(jTableLocaisJogos.AUTO_RESIZE_OFF);
        jTableLocaisJogos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconectar();
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadCampo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonpesquisar;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCOD;
    private javax.swing.JTable jTableLocaisJogos;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables
}
