package view;

import modeloConnection.ConexaoBD;

/**
 *
 * @author F-BRAGA
 */
public class TelaPrincipal extends javax.swing.JFrame {
    ConexaoBD conecta = new ConexaoBD();
    TelaCadCampo tela = new TelaCadCampo();
    TelaCadUsuario telaUser = new TelaCadUsuario();
    TelaPeladeiro telaPe = new TelaPeladeiro();
    
    
    public TelaPrincipal(String usuario) {
        initComponents();
        jLabelUsuario.setText(usuario);
        conecta.conexao();
    }

    private TelaPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jFundoPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadCapQuadra = new javax.swing.JMenuItem();
        jMenuItemPeladas = new javax.swing.JMenuItem();
        jMenuUsuario = new javax.swing.JMenuItem();
        jMenuItemPeladeiros = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("Usuário:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 474, 70, 20);
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(60, 474, 190, 20);

        jFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo principal 4.jpg"))); // NOI18N
        getContentPane().add(jFundoPrincipal);
        jFundoPrincipal.setBounds(0, 0, 850, 470);

        jMenuCadastro.setText("Cadastro");

        jMenuItemCadCapQuadra.setText("Campos/Quadras");
        jMenuItemCadCapQuadra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadCapQuadraActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadCapQuadra);

        jMenuItemPeladas.setText("Peladas");
        jMenuItemPeladas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPeladasActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemPeladas);

        jMenuUsuario.setText("Usuários");
        jMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuUsuario);

        jMenuItemPeladeiros.setText("Peladeiros");
        jMenuItemPeladeiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPeladeirosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemPeladeiros);

        jMenuBar1.add(jMenuCadastro);

        jMenuRelatorios.setText("Relatórios");
        jMenuBar1.add(jMenuRelatorios);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(861, 545));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadCapQuadraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadCapQuadraActionPerformed
        if(tela==null){
        TelaCadCampo tela = new TelaCadCampo();
        tela.setVisible(true); 
        tela.setResizable(false);
        }else{
        tela.setVisible(true); 
        tela.setResizable(false);    
        }
    }//GEN-LAST:event_jMenuItemCadCapQuadraActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        conecta.desconectar();
        System.exit(0);
        
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioActionPerformed
        if(telaUser==null){
        TelaCadUsuario telaUser = new TelaCadUsuario();
        telaUser.setVisible(true); 
        telaUser.setResizable(false);
        }else{
        telaUser.setVisible(true); 
        telaUser.setResizable(false);    
        }
    }//GEN-LAST:event_jMenuUsuarioActionPerformed

    private void jMenuItemPeladeirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPeladeirosActionPerformed
        if(telaPe==null){
        TelaPeladeiro telaPe = new TelaPeladeiro();
        telaPe.setVisible(true); 
        telaPe.setResizable(false);
        }else{
        telaPe.setVisible(true); 
        telaPe.setResizable(false);    
        }
    }//GEN-LAST:event_jMenuItemPeladeirosActionPerformed

    private void jMenuItemPeladasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPeladasActionPerformed
        
    }//GEN-LAST:event_jMenuItemPeladasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jFundoPrincipal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItemCadCapQuadra;
    private javax.swing.JMenuItem jMenuItemPeladas;
    private javax.swing.JMenuItem jMenuItemPeladeiros;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenuItem jMenuUsuario;
    // End of variables declaration//GEN-END:variables
}
